### ISSUE TITLE
Please plugin device to login - Ledger Nano S

### ISSUE THREAD

**Issue by Osolong2** [ontio/documentation#134]
I am on latest version of Ledger Nano S firmware 1.4.2 - I have followed the detailed instructions, tried reinstalling the Ontology app on the Ledger, and cannot login with Ledger.

On the Ledger screen that says "Hello ONT", I click to "Login with Ledger" in O Wallet and it says "Please plugin device to login."

**Comment by MickWang** [comment]
we fixed these problems in v0.8.1. Please download the new version and try again.
https://github.com/ontio/OWallet/releases
