### ISSUE TITLE
根据随机顺序来决定主链选择的优先级，感觉不是很好，主链最好是竞争出来的，而不是靠天意

### ISSUE THREAD

**Issue by dushaobindoudou** [ontio/documentation#140]
能不能理解为 恶意的块 还是有概率被打包到主链上？ 如果是这样的话 这种思路还是有改进的空间的

**Comment by Honglei-Cong** [comment]
根据随机顺序来决定主链选择的优先级是proposal的优先级，每个proposal都需要其它节点verify后才可能成为正式的区块。恶意的块不会被打包到主链上。
主链最好是竞争出来的，竞争是难以公平的。
