### ISSUE TITLE
Api for send transaction for mainnet

### ISSUE THREAD

**Issue by shweta037** [ontio/documentation#173]
Any one have idea to broadcast transaction using api..I am trying to work in trading for ontology ..I am using node js .

**Comment by xizho10** [comment]
http://dev-docs.ont.io      ts-ssdk

**Comment by shweta037** [comment]
> http://dev-docs.ont.io ts-sdk

Thanks for the reply i am already following this document...

Not understanding this...


//sign transaction before send it
import {RestClient, CONST, TransactionBuilder} from 'ontology-ts-sdk'

//we already got the transaction we created before

//we have to sign the transaction before sent it
//Use user's private key to sign the transaction
TransactionBuilder.signTransaction(tx, privateKey)
//If the transaction needs more than one signatures. We can add signature to it.
//TransactionBuilder.addSign(tx, otherPrivateKey)

const rest = new RestClient(CONST.TEST_ONT_URL.REST_URL);
rest.sendRawTransaction(tx.serialize()).then(res => {
	console.log(res)	
})



above this we have done all...


what is this actually???

CONST.TEST_ONT_URL.REST_URL

Can you please help....from where to get this CONST and test_ONT_URL and REST_URL

**Comment by shweta037** [comment]
this.payer.serialize is not a function getting this error.............

**Comment by NashMiao** [comment]
This has nothing to do with documentation, and you're using the ontology-ts-sdk, so please open any issues at https://github.com/ontio/ontology-ts-sdk.
