### ISSUE TITLE
sample wasm smart contract is buggy

### ISSUE THREAD

**Issue by yufengshen** [ontio/documentation#53]
char * concat(char * a, char * b){
	int lena = arrayLen(a);
	int lenb = arrayLen(b);
	char * res = (char *)malloc((lena + lenb)*sizeof(char));
	for (int i = 0 ;i < lena ;i++){
		res[i] = a[i];
	}

	for (int j = 0; j < lenb ;j++){
		res[lenb + j] = b[j];
	}
	return res;
}

with almost ~1B USD in market capital, you can't even get the most basic smart contract sample
correct, LOL ....

**Comment by JasonZhouPW** [comment]
thank you for your kindly reminding, our wasm contracts is still in developing and testing ,and this “concat” function is moved to API level with golang code. welcome to give more suggestions ,thank you very much.
