### ISSUE TITLE
[Recommendation] Put each API in folders per language

### ISSUE THREAD

**Issue by jonatanblockchain** [ontio/documentation#6]
Create a similar folder structure like NEO documentation per language and each api or resftulapi in diferents files. Something similar to:

![sin titulo](https://user-images.githubusercontent.com/29895459/38084819-a1142aaa-334e-11e8-9761-417b9a255901.png)

**Comment by xbxlxp** [comment]
Thanks for your recommendation! We will improve gradually later.

**Comment by qlovn** [comment]
Yeah, that's smart. Makes it easier I guess.
