### ISSUE TITLE
README's broken

### ISSUE THREAD

**Issue by WyattMufson** [ontio/documentation#617]
You cannot use `<style>` tags in Markdown on Github, like here: 
- https://github.com/ontio/documentation/blob/master/dev-website-docs/docs-en/README.md
- https://github.com/ontio/documentation/blob/master/dev-website-docs/docs-cn/README.md

**Comment by WyattMufson** [comment]
@MickWang someone should fix this

**Comment by NashMiao** [comment]
@WyattMufsonHi, this document is wrote for [this](https://dev-docs.ont.io/) page.

**Comment by WyattMufson** [comment]
@NashMiao ah ok, thanks for clarifying
