### ISSUE TITLE
Why 404

### ISSUE THREAD

**Issue by chenzhitong** [ontio/documentation#645]
![image](https://user-images.githubusercontent.com/6295602/60857473-4d97a780-a23d-11e9-9236-e58d36755436.png)

Why jump on page 404 and then jump to document

**Comment by sulingxiao** [comment]
I will change it to welcome ！

**Comment by sulingxiao** [comment]
Thank you for your reminder, we will fix this problem asap.

**Comment by sulingxiao** [comment]
fixed
